src/Entity/Logboek.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogboekRepository")
 */
class Logboek
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $brief_nr;

    /**
     * @ORM\Column(type="date")
     */
    private $datum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chauffeur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Truck")
     * @ORM\JoinColumn(nullable=false)
     */
    private $truck;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $kubs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $laadplaats;

    /**
     * @ORM\Column(type="time")
     */
    private $vertrektijd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bestemming;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBriefNr(): ?int
    {
        return $this->brief_nr;
    }

    public function setBriefNr(int $brief_nr): self
    {
        $this->brief_nr = $brief_nr;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getChauffeur(): ?User
    {
        return $this->chauffeur;
    }

    public function setChauffeur(?User $chauffeur): self
    {
        $this->chauffeur = $chauffeur;

        return $this;
    }

    public function getTruck(): ?Truck
    {
        return $this->truck;
    }

    public function setTruck(?Truck $truck): self
    {
        $this->truck = $truck;

        return $this;
    }

    public function getKubs()
    {
        return $this->kubs;
    }

    public function setKubs($kubs): self
    {
        $this->kubs = $kubs;

        return $this;
    }

    public function getLaadplaats(): ?string
    {
        return $this->laadplaats;
    }

    public function setLaadplaats(string $laadplaats): self
    {
        $this->laadplaats = $laadplaats;

        return $this;
    }

    public function getVertrektijd(): ?\DateTimeInterface
    {
        return $this->vertrektijd;
    }

    public function setVertrektijd(\DateTimeInterface $vertrektijd): self
    {
        $this->vertrektijd = $vertrektijd;

        return $this;
    }

    public function getBestemming(): ?string
    {
        return $this->bestemming;
    }

    public function setBestemming(string $bestemming): self
    {
        $this->bestemming = $bestemming;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(?string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }
}

src/Form/LogboekType.php
<?php

namespace App\Form;

use App\Entity\Logboek;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogboekType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('brief_nr')
            ->add('datum', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('kubs')
            ->add('laadplaats')
            ->add('vertrektijd')
            ->add('bestemming')
            ->add('evenement')
            ->add('user')
            ->add('chauffeur')
            ->add('truck')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logboek::class,
        ]);
    }
}

src/Controller/LogboekController.php
<?php

namespace App\Controller;

use App\Entity\Logboek;
use App\Form\LogboekType;
use App\Repository\LogboekRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/logboek")
 */
class LogboekController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    /**
     * @Route("/", name="logboek_index", methods={"GET"})
     */
    public function index(LogboekRepository $logboekRepository): Response
    {
        //$user = $this->getUser();
        $user = $this->getUser()->getId();
        if ($this->security->isGranted('ROLE_SUPER_ADMIN')) {


            return $this->render('logboek/index.html.twig', [
                'logboeks' => $logboekRepository->findAll(),
            ]);
        }

        elseif ($this->security->isGranted('ROLE_TRUCK')) {
            return $this->render('logboek/index.html.twig', [
                'logboeks' => $logboekRepository->findBy(['chauffeur' => $user]),
            ]);
        }
        else {
        return $this->render('logboek/index.html.twig', [
            'logboeks' => $logboekRepository->findBy(['user' => $user]),
        ]);
    }


    }

    /**
     * @Route("/new", name="logboek_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->security->isGranted('ROLE_SUPER_ADMIN')) {
            $logboek = new Logboek();
            $logboek->setDatum(new \DateTime('now'));
            $form = $this->createForm(LogboekType::class, $logboek);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($logboek);
                $entityManager->flush();

                return $this->redirectToRoute('logboek_index');
            }

            return $this->render('logboek/new.html.twig', [
                'logboek' => $logboek,
                'form' => $form->createView(),
            ]);
        }
        else {
            return $this->render("default/noacces.html.twig");
        }
    }

    /**
     * @Route("/{id}", name="logboek_show", methods={"GET"})
     */
    public function show(Logboek $logboek): Response
    {
        return $this->render('logboek/show.html.twig', [
            'logboek' => $logboek,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="logboek_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Logboek $logboek): Response
    {
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('logboek_index', [
                'id' => $logboek->getId(),
            ]);
        }

        return $this->render('logboek/edit.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logboek_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Logboek $logboek): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logboek->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($logboek);
            $entityManager->flush();
        }

        return $this->redirectToRoute('logboek_index');
    }
}

templates/logboek/_delete_form.html.twig
<form method="post" action="{{ path('logboek_delete', {'id': logboek.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logboek.id) }}">
    <button class="btn">Delete</button>
</form>

templates/logboek/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logboek{% endblock %}

{% block body %}
    <h1>Edit Logboek</h1>

    {{ include('logboek/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('logboek_index') }}">back to list</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}

templates/logboek/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek index{% endblock %}

{% block body %}
    <h1>Logboek index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Brief_nr</th>
                <th>Datum</th>
                <th>Kubs</th>
                <th>Laadplaats</th>
                <th>Vertrektijd</th>
                <th>Bestemming</th>
                <th>Evenement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for logboek in logboeks %}

            <tr>
                <td>{{ logboek.id }}</td>
                <td>{{ logboek.briefNr }}</td>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d') : '' }}</td>
                <td>{{ logboek.kubs }}</td>
                <td>{{ logboek.laadplaats }}</td>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
                <td>{{ logboek.bestemming }}</td>
                <td>{{ logboek.evenement }}</td>
                <td>
                    <a href="{{ path('logboek_show', {'id': logboek.id}) }}">show</a>
                    {% if is_granted("ROLE_TRUCK") %}
                    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('logboek_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/logboek/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logboek{% endblock %}

{% block body %}
    <h1>Create new Logboek</h1>

    {{ include('logboek/_form.html.twig') }}

    <a href="{{ path('logboek_index') }}">back to list</a>
{% endblock %}

templates/logboek/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek{% endblock %}

{% block body %}
    <h1>Logboek</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ logboek.id }}</td>
            </tr>
            <tr>
                <th>Brief_nr</th>
                <td>{{ logboek.briefNr }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Kubs</th>
                <td>{{ logboek.kubs }}</td>
            </tr>
            <tr>
                <th>Laadplaats</th>
                <td>{{ logboek.laadplaats }}</td>
            </tr>
            <tr>
                <th>Vertrektijd</th>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Bestemming</th>
                <td>{{ logboek.bestemming }}</td>
            </tr>
            <tr>
                <th>Evenement</th>
                <td>{{ logboek.evenement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('logboek_index') }}">back to list</a>
    {% if is_granted(["ROLE_SUPER_ADMIN"]) %}
        <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
    {% elseif is_granted(["ROLE_TRUCK"]) %}
        <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
    {% endif %}


    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}